# Project
version=0.0.9
group=cn.jawbreakers.candycraftce

# Common
modName=CandyCraft Community Edition
modAuthor=the JawBreaker's(Bread_NiceCat, CATsightGK), Star_Ocean_Sama
modId=candycraftce
license=GPL-3.0
credits=Valentin4311(for the original work)
description=Integrated and ported Valentin4311's CandyCraft mod and ochotonida's CandyWorld mod to 1.20.1

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
